/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export type AllSanitySchemaTypes =
  | Announcement
  | Exhibit
  | Exhibition
  | ExhibitReference
  | Geopoint
  | SanityAssetSourceData
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageAssetReference
  | SanityImageCrop
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageMetadata
  | SanityImagePalette
  | SanityImagePaletteSwatch
  | SchoolInfo
  | Slug

export type Announcement = {
  _createdAt: string
  _id: string
  _rev: string
  _type: "announcement"
  _updatedAt: string
  category?: "contests" | "events" | "schedule" | "technical" | "updates"
  content?: string
  date?: string
  isPinned?: boolean
  priority?: "important" | "medium" | "normal"
  title?: string
}

export type Exhibit = {
  _createdAt: string
  _id: string
  _rev: string
  _type: "exhibit"
  _updatedAt: string
  arModelUrl?: string
  description?: string
  image?: {
    _type: "image"
    asset?: SanityImageAssetReference
    crop?: SanityImageCrop
    hotspot?: SanityImageHotspot
    media?: unknown
  }
  positionX?: number
  positionY?: number
  title?: string
}

export type Exhibition = {
  _createdAt: string
  _id: string
  _rev: string
  _type: "exhibition"
  _updatedAt: string
  coverImage?: {
    _type: "image"
    asset?: SanityImageAssetReference
    crop?: SanityImageCrop
    hotspot?: SanityImageHotspot
    media?: unknown
  }
  curator?: string
  date?: string
  description?: string
  exhibits?: Array<
    ExhibitReference & {
      _key: string
    }
  >
  hasAR?: boolean
  slug?: Slug
  title?: string
}

export type ExhibitReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "exhibit"
}

export type Geopoint = {
  _type: "geopoint"
  alt?: number
  lat?: number
  lng?: number
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  id?: string
  name?: string
  url?: string
}

export type SanityFileAsset = {
  _createdAt: string
  _id: string
  _rev: string
  _type: "sanity.fileAsset"
  _updatedAt: string
  altText?: string
  assetId?: string
  description?: string
  extension?: string
  label?: string
  mimeType?: string
  originalFilename?: string
  path?: string
  sha1hash?: string
  size?: number
  source?: SanityAssetSourceData
  title?: string
  uploadId?: string
  url?: string
}

export type SanityImageAsset = {
  _createdAt: string
  _id: string
  _rev: string
  _type: "sanity.imageAsset"
  _updatedAt: string
  altText?: string
  assetId?: string
  description?: string
  extension?: string
  label?: string
  metadata?: SanityImageMetadata
  mimeType?: string
  originalFilename?: string
  path?: string
  sha1hash?: string
  size?: number
  source?: SanityAssetSourceData
  title?: string
  uploadId?: string
  url?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  bottom?: number
  left?: number
  right?: number
  top?: number
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  aspectRatio?: number
  height?: number
  width?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  height?: number
  width?: number
  x?: number
  y?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  blurHash?: string
  dimensions?: SanityImageDimensions
  hasAlpha?: boolean
  isOpaque?: boolean
  location?: Geopoint
  lqip?: string
  palette?: SanityImagePalette
  thumbHash?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

// Source: schema.json
export type SchoolInfo = {
  _createdAt: string
  _id: string
  _rev: string
  _type: "schoolInfo"
  _updatedAt: string
  contacts?: string
  description?: Array<{
    _key: string
    _type: "block"
    children?: Array<{
      _key: string
      _type: "span"
      marks?: Array<string>
      text?: string
    }>
    level?: number
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      _key: string
      _type: "link"
      href?: string
    }>
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal"
  }>
  goals?: Array<string>
}

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export declare const internalGroqTypeReferenceTo: unique symbol
