import "../styles/globals.css"
import type { Metadata } from "next"

import { Footer } from "@widgets/footer"
import { Header } from "@widgets/header"

import { font } from "../styles/font"

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

export function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className="light" lang="en">
      <body className={`${font.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
